BUG: fix indexing errors with range objects
With Python 3.4, we are getting indexing errors trying to index into
array with range objects - e.g.:

```
    idx_bool[idx] = 1
IndexError: unsupported iterator index
```

where `idx` is a range object.  See:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/211972130/log.txt

Use np.arange instead of range.